name: yo_contrato_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  dartz: ^0.10.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGOOO.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGOOO.png
    - assets/images/qr_placeholder.png
  fonts:
    - family: Stabillo Medium 500
      fonts:
        - asset: assets/fonts/Stabillo Medium 500.ttf
          weight: 700